name: 🏠 Add New Place
description: Submit a new place to be added to the PMC Map
title: "[PLACE] Add new place: "
labels: ["enhancement", "place", "community-contribution"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to the PMC Map! Please fill out all required fields below to add a new place.
        
        **Important:** Make sure the place doesn't already exist by checking the [current places](https://github.com/tristanhabemont/PMC-Map/tree/main/public/data/places).

  - type: input
    id: place-id
    attributes:
      label: Place ID
      description: A unique identifier for this place (lowercase, underscore-separated)
      placeholder: "my_cool_base"
    validations:
      required: true

  - type: input
    id: place-name
    attributes:
      label: Place Name
      description: The display name for this place
      placeholder: "My Cool Base"
    validations:
      required: true

  - type: dropdown
    id: dimension
    attributes:
      label: Dimension
      description: Which dimension is this place located in?
      options:
        - overworld
        - nether
        - end
    validations:
      required: true

  - type: input
    id: coordinates-x
    attributes:
      label: X Coordinate
      description: The X coordinate of the place
      placeholder: "100"
    validations:
      required: true

  - type: input
    id: coordinates-y
    attributes:
      label: Y Coordinate
      description: The Y coordinate of the place
      placeholder: "64"
    validations:
      required: true

  - type: input
    id: coordinates-z
    attributes:
      label: Z Coordinate
      description: The Z coordinate of the place
      placeholder: "200"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of this place (optional)
      placeholder: "A large farming complex with automated crop systems"

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated tags to categorize this place (optional)
      placeholder: "farm, automated, redstone"

  - type: input
    id: nearest-portal
    attributes:
      label: Nearest Portal ID
      description: The ID of the nearest portal to this place (optional)
      placeholder: "main_hub_portal"

  - type: textarea
    id: json-data
    attributes:
      label: Generated JSON (Auto-filled)
      description: "This will be auto-generated based on your inputs above. Please don't edit manually."
      render: json
      value: |
        {
          "id": "",
          "name": "",
          "dimension": "",
          "coordinates": { "x": 0, "y": 0, "z": 0 },
          "tags": [],
          "description": "",
          "nearestPortalId": ""
        }

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have verified this place doesn't already exist
          required: true
        - label: The coordinates are accurate
          required: true
        - label: I have permission to add this place to the public map
          required: true

  - type: markdown
    attributes:
      value: |
        ## What happens next?
        
        1. Our automated validation will check your JSON format
        2. If validation passes, a maintainer will review your submission
        3. Once approved, your place will be added to the map!
        
        **File location:** Your place will be saved as `public/data/places/{place-id}.json`