name: 🌀 Ajouter un nouveau portail
description: Soumettre un nouveau portail à ajouter à PMC Plan
title: "🌀 Ajouter un nouveau portail : "
labels: 
  - community-contribution
  - portal
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Merci de contribuer à PMC Plan ! Veuillez remplir tous les champs requis ci-dessous pour ajouter un nouveau portail.
        Pour vous aider, des exemples de [lieux](https://github.com/Sukikui/PMC-Plan/tree/main/public/data/place_examples) et de [portails](https://github.com/Sukikui/PMC-Plan/tree/main/public/data/portal_examples) sont disponibles.

        **Important :** Assurez-vous que le portail n'existe pas déjà en consultant les [portails actuels](https://github.com/Sukikui/PMC-Plan/tree/main/public/data/portals).

  - type: input
    id: portal-id
    attributes:
      label: ID du portail
      description: |
        Un identifiant unique pour ce portail (minuscules, séparé par des underscores).
        **Important :** Merci d'utiliser le même identifiant en ce qui concerne les portails liés entre l'Overworld et le Nether. Ne faites pas mention du monde dans lequel se trouve votre portail dans l'identifiant, ceci est automatiquement pris en charge suivant le monde que vous choisirez ci-dessous.
      placeholder: "portail_village_suki"
    validations:
      required: true

  - type: input
    id: portal-name
    attributes:
      label: Nom du portail
      description: Le nom d'affichage pour ce portail
      placeholder: "Portail du village de Suki"
    validations:
      required: true

  - type: dropdown
    id: world
    attributes:
      label: Monde
      options:
        - overworld
        - nether
    validations:
      required: true

  - type: input
    id: coordinates-x
    attributes:
      label: Coordonnée X
      placeholder: "0"
    validations:
      required: true

  - type: input
    id: coordinates-y
    attributes:
      label: Coordonnée Y
      placeholder: "64"
    validations:
      required: true

  - type: input
    id: coordinates-z
    attributes:
      label: Coordonnée Z
      placeholder: "0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description (optionnel)
      description: Une brève description de ce portail. Si le portail que vous souhaitez ajouter se trouve coté Nether et que son portail lié coté Overworld est déjà inscrit sur PMC Plan, inutile d'ajouter une description.
      placeholder: "Donne l'accès sur l'entrée principale du village de Suki."

  - type: checkboxes
    id: checklist
    attributes:
      label: Liste de vérification
      description: Veuillez confirmer ce qui suit
      options:
        - label: J'ai vérifié que ce portail n'existe pas déjà
          required: true
        - label: Les coordonnées sont exactes
          required: true
        - label: J'utilise le même identifiant en ce qui concerne les portails liés entre l'Overworld et le Nether
          required: true

  - type: markdown
    attributes:
      value: |
        ## Que se passe-t-il ensuite ?
        
        1. Une fois cette issue soumise, le système validera automatiquement vos données
        2. Si la validation réussit, une Pull Request sera créée automatiquement avec le fichier JSON
        3. Un mainteneur examinera votre soumission
        4. Une fois approuvé, votre portail sera ajouté à PMC Plan !
        
        **Emplacement du fichier :** Votre portail sera sauvegardé comme `public/data/portals/{id-portail}_{monde}.json`