name: 🌀 Ajouter un nouveau portail
description: Soumettre un nouveau portail à ajouter à la carte PMC
title: "[PORTAIL] Ajouter un nouveau portail : "
labels: ["enhancement", "portal", "community-contribution"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Merci de contribuer à la carte PMC ! Veuillez remplir tous les champs requis ci-dessous pour ajouter un nouveau portail.
        
        **Important :** Assurez-vous que le portail n'existe pas déjà en consultant les [portails actuels](https://github.com/tristanhabemont/PMC-Map/tree/main/public/data/portals).

  - type: input
    id: portal-id
    attributes:
      label: ID du portail
      description: Un identifiant unique pour ce portail (minuscules, séparé par des underscores)
      placeholder: "portail_ma_base_ow"
    validations:
      required: true

  - type: input
    id: portal-name
    attributes:
      label: Nom du portail
      description: Le nom d'affichage pour ce portail
      placeholder: "Portail de ma base (Overworld)"
    validations:
      required: true

  - type: dropdown
    id: world
    attributes:
      label: Monde
      description: Dans quel monde ce portail est-il situé ?
      options:
        - overworld
        - nether
        - end
    validations:
      required: true

  - type: input
    id: coordinates-x
    attributes:
      label: Coordonnée X
      description: La coordonnée X du portail
      placeholder: "100"
    validations:
      required: true

  - type: input
    id: coordinates-y
    attributes:
      label: Coordonnée Y
      description: La coordonnée Y du portail
      placeholder: "64"
    validations:
      required: true

  - type: input
    id: coordinates-z
    attributes:
      label: Coordonnée Z
      description: La coordonnée Z du portail
      placeholder: "200"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Une brève description de ce portail (optionnel)
      placeholder: "Portail reliant à la base principale dans le nether"

  - type: textarea
    id: json-data
    attributes:
      label: JSON généré (Auto-rempli)
      description: "Ceci sera généré automatiquement basé sur vos entrées ci-dessus. Veuillez ne pas éditer manuellement."
      render: json
      value: |
        {
          "id": "",
          "name": "",
          "world": "",
          "coordinates": { "x": 0, "y": 0, "z": 0 },
          "description": ""
        }

  - type: checkboxes
    id: checklist
    attributes:
      label: Liste de vérification
      description: Veuillez confirmer ce qui suit
      options:
        - label: J'ai vérifié que ce portail n'existe pas déjà
          required: true
        - label: Les coordonnées sont exactes
          required: true
        - label: J'ai la permission d'ajouter ce portail à la carte publique
          required: true

  - type: markdown
    attributes:
      value: |
        ## Que se passe-t-il ensuite ?
        
        1. Notre validation automatique vérifiera le format de votre JSON
        2. Si la validation réussit, un mainteneur examinera votre soumission
        3. Une fois approuvé, votre portail sera ajouté à la carte !
        
        **Emplacement du fichier :** Votre portail sera sauvegardé comme `public/data/portals/{portal-id}.json`