name: 🏠 Ajouter un nouveau lieu
description: Soumettre un nouveau lieu à ajouter à PMC Plan
title: "🏠 Ajouter un nouveau lieu : "
labels: 
  - community-contribution
  - place
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Merci de contribuer à PMC Plan ! Veuillez remplir tous les champs requis ci-dessous pour ajouter un nouveau lieu.
        Pour vous aider, des exemples de [lieux](https://github.com/Sukikui/PMC-Plan/tree/main/public/data/place_examples) et de [portails](https://github.com/Sukikui/PMC-Plan/tree/main/public/data/portal_examples) sont disponibles.
        
        **Important :** Assurez-vous que le lieu n'existe pas déjà en consultant les [lieux actuels](https://github.com/Sukikui/PMC-Plan/tree/main/public/data/places).

  - type: input
    id: place-id
    attributes:
      label: ID du lieu
      description: Un identifiant unique pour ce lieu (minuscules, séparé par des underscores)
      placeholder: "village_suki"
    validations:
      required: true

  - type: input
    id: place-name
    attributes:
      label: Nom du lieu
      description: Le nom d'affichage pour ce lieu
      placeholder: "Village de Suki"
    validations:
      required: true

  - type: dropdown
    id: world
    attributes:
      label: Monde
      options:
        - overworld
        - nether
    validations:
      required: true

  - type: input
    id: coordinates-x
    attributes:
      label: Coordonnée X
      placeholder: "0"
    validations:
      required: true

  - type: input
    id: coordinates-y
    attributes:
      label: Coordonnée Y
      placeholder: "64"
    validations:
      required: true

  - type: input
    id: coordinates-z
    attributes:
      label: Coordonnée Z
      placeholder: "0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Une brève description de ce lieu (optionnel)
      placeholder: "Village de Suki au sein duquel de nombreux secrets et trésors sont gardés à tout jamais..."

  - type: input
    id: tags
    attributes:
      label: Étiquettes
      description: Étiquettes séparées par des virgules pour catégoriser ce lieu (optionnel)
      placeholder: "ferme, ville, magasin"

  - type: input
    id: portals
    attributes:
      label: Portails liés
      description: IDs des portails associés à ce lieu, séparés par des virgules (optionnel)
      placeholder: "portail_village_suki, portail_autre_lieu"

  - type: checkboxes
    id: checklist
    attributes:
      label: Liste de vérification
      description: Veuillez confirmer ce qui suit
      options:
        - label: J'ai vérifié que ce lieu n'existe pas déjà
          required: true
        - label: Les coordonnées sont exactes
          required: true
        - label: J'ai indiqué l'ensemble des portails liés à ce lieu
          required: true

  - type: markdown
    attributes:
      value: |
        ## Que se passe-t-il ensuite ?
        
        1. Une fois cette issue soumise, le système validera automatiquement vos données
        2. Si la validation réussit, une Pull Request sera créée automatiquement avec le fichier JSON
        3. Un mainteneur examinera votre soumission
        4. Une fois approuvé, votre lieu sera ajouté à PMC Plan !
        
        **Emplacement du fichier :** Votre lieu sera sauvegardé comme `public/data/places/{place-id}.json`