export const MANAGEMENT_LIST_PAGE_SIZE = 7;
export const MANAGEMENT_LIST_ROW_HEIGHT_PX = 60;
export const MANAGEMENT_LIST_VIEWPORT_HEIGHT_PX =
  MANAGEMENT_LIST_PAGE_SIZE * MANAGEMENT_LIST_ROW_HEIGHT_PX;
