name: API Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Start Next.js production server
      run: npm run start &

    - name: Wait for server to be ready
      run: |
        for i in {1..60}; do
          if curl -f http://localhost:3000/api/nether-address?x=0&z=0 >/dev/null 2>&1; then
            echo "✅ Server is ready"
            sleep 10
            break
          fi
          echo "⏳ Waiting for server... ($i/60)"
          sleep 5
        done

    - name: Run endpoint validation tests  
      run: npm run test:endpoints
