name: Validate Community Contributions

on:
  pull_request:
  issues:
    types: [opened, edited]
  workflow_run:
    workflows: ["Validate Community Contributions"]
    types: [completed]
    branches: [main]

jobs:
  validate-pr-files:
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    name: Validate Files in PR
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install ajv
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            public/data/places/**/*.json
            public/data/portals/**/*.json
            
      - name: Validate Changed Files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            node .github/scripts/validate-data.js "$file"
          done

      - name: Get changed images
        id: changed-images
        uses: tj-actions/changed-files@v41
        with:
          files: public/data/place_images/**/*.{png,jpg,jpeg,gif}

      - name: Validate Image Filenames
        if: steps.changed-images.outputs.any_changed == 'true'
        run: |
          node .github/scripts/validate-images.js ${{ steps.changed-images.outputs.all_changed_files }}

  validate-issue:
    if: github.event_name == 'issues' && (contains(github.event.issue.labels.*.name, 'place') || contains(github.event.issue.labels.*.name, 'portal'))
    runs-on: ubuntu-latest
    name: Validate Issue Template Data and Create PR
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install ajv node-fetch@2
          
      - name: Extract and validate JSON from issue
        uses: actions/github-script@v7
        with:
          script: |
            const { validateIssueData } = require('./.github/scripts/validate-issue.js');
            await validateIssueData(github, context);