export const SOCIAL_PREVIEW_WIDTH = 1200;
export const SOCIAL_PREVIEW_HORIZONTAL_PADDING = 46;
export const SOCIAL_PREVIEW_FOOTER_GAP = 64;
export const SOCIAL_PREVIEW_HEADER_HEIGHT = 132;
export const SOCIAL_PREVIEW_FOOTER_HEIGHT = 150;
export const SOCIAL_PREVIEW_IMAGE_HEIGHT = 675;
export const SOCIAL_PREVIEW_HEIGHT = (
  SOCIAL_PREVIEW_HEADER_HEIGHT
  + SOCIAL_PREVIEW_IMAGE_HEIGHT
  + SOCIAL_PREVIEW_FOOTER_HEIGHT
);
